// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdFyuyrRR4WO7oc6WuBONH0bnfu6cOFis',
    appId: '1:393785745373:web:d05133f75d225414c06034',
    messagingSenderId: '393785745373',
    projectId: 'sartheeai',
    authDomain: 'sartheeai.firebaseapp.com',
    storageBucket: 'sartheeai.firebasestorage.app',
    measurementId: 'G-CYGN8V3KW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrYWnu33ZKWFdew1X1hHSYJQ6VgTWGPCc',
    appId: '1:393785745373:android:f8faa30c2c943bacc06034',
    messagingSenderId: '393785745373',
    projectId: 'sartheeai',
    storageBucket: 'sartheeai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoF3beb0ltrN33GfrSI0JKqu9jrGBtud0',
    appId: '1:393785745373:ios:5c09d8c734441945c06034',
    messagingSenderId: '393785745373',
    projectId: 'sartheeai',
    storageBucket: 'sartheeai.firebasestorage.app',
    iosClientId:
        '393785745373-7pqr8g8mvt4ikf2a1ovl533qiescv72a.apps.googleusercontent.com',
    iosBundleId: 'com.sartheeai.sartheeAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoF3beb0ltrN33GfrSI0JKqu9jrGBtud0',
    appId: '1:393785745373:ios:5c09d8c734441945c06034',
    messagingSenderId: '393785745373',
    projectId: 'sartheeai',
    storageBucket: 'sartheeai.firebasestorage.app',
    iosClientId:
        '393785745373-7pqr8g8mvt4ikf2a1ovl533qiescv72a.apps.googleusercontent.com',
    iosBundleId: 'com.sartheeai.sartheeAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdFyuyrRR4WO7oc6WuBONH0bnfu6cOFis',
    appId: '1:393785745373:web:be8835c961ea714dc06034',
    messagingSenderId: '393785745373',
    projectId: 'sartheeai',
    authDomain: 'sartheeai.firebaseapp.com',
    storageBucket: 'sartheeai.firebasestorage.app',
    measurementId: 'G-WTE77GX198',
  );
}
